### ISSUE TITLE
Support mongodb selection in create keystone-next-app

### ISSUE THREAD

**Issue by tranlehaiquan** [keystonejs/create-keystone-next-app#27]
In the create keystone-next-app I can't select Mongodb? Is it doesn't support or not support yet? And any way to solve this? Thank you.

<img width="1306" alt="Screen Shot 2021-03-15 at 11 05 38" src="https://user-images.githubusercontent.com/17347993/111102357-77f74780-857e-11eb-8687-21a75f22e3a2.png">

**Comment by timleslie** [comment]
Hi @tranlehaiquan,

As part of our [roadmap](https://next.keystonejs.com/roadmap#streamlined-back-end-with-prisma) we're moving towards Prisma being our primary backend. As such, support for MongoDB in `create-keystone-next-app` will be dependent on Prisma support for MongoDB, which is currently [in progress](https://www.prisma.io/docs/mongodb).

When this support is available, we'll add it to `create-keystone-next-app`.
